server:
  port: 10007

spring:
  jackson:
    time-zone: GMT+8
    dateFormat: yyyy-MM-dd HH:mm:ss
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.10.131:8858
      web-context-unify: false # 默认是启动链路收敛，这里给放开