server:
  port: 10010
spring:
  application:
    name: study-mthread
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.131:3306/temp_tp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1024KangYong@MySQL

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
