server:
  port: 10001
spring:
  application:
    name: study-springboot-redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.157.44.168:3306/sales_online?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: tsERDxJOxbSk775w
  redis:
    host: 82.157.44.168
    port: 6379
    password: VMoEXKYYAwb6ykzg

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
