server:
  port: 10001
spring:
  application:
    name: study-springboot-redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.37.42.142:3306/leadnews_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: leadnewsAdmin
    password: 1024KangYong
  redis:
    host: 121.37.42.142
    port: 6379
    password: 1024KangYong@Redis

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
