server:
  port: 10005
spring:
  application:
    name: study-sentinel-order
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.10.131:8858
      web-context-unify: false # 默认是启动链路收敛，这里给放开