server:
  port: 10011
spring:
  application:
    name: study-springboot-sharding-jdbc
  shardingsphere:
    # 配置数据源具体内容
    datasource:
      names: ds1
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.10.131:3306/sharding_sphere?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: 1024KangYong@MySQL
    # 指定order表的分布情况，配置表在那个数据库中，表名称是什么
    sharding:
      tables:
        orders:
          actual-data-nodes: ds1.orders_$->{1..2}
          # 指定orders表里主键id生成策略
          key-generator:
            column: id
            type: SNOWFLAKE
          # 指定分片策略。根据id的奇偶性来判断插入到哪个表
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: orders_${id%2+1}
    props:
      sql:
        # 打开SQL输出日志
        show: true

# 整合mybatis
mybatis:
  type-aliases-package: top.kangyong.sbsj.mapper
