server:
  port: 10001
spring:
  application:
    name: study-springboot-property
study-property:
    msg-template-list:
      - wxAppId: 123456
        opening: 1
        priceChanges: 2
        subscribe: 3
      - wxAppId: 7890
        opening: 4
        priceChanges: 5
        subscribe: 6
    province-map:
      110000: 北京市
      120000: 天津市
      130000: 河北省
      140000: 山西省
      150000: 内蒙古自治区
      210000: 辽宁省
      220000: 吉林省
      230000: 黑龙江省
      310000: 上海市
      320000: 江苏省
      330000: 浙江省
      340000: 安徽省



